[tool.poetry]
name = "money-utils"
version = "0.1.0"
description = ""
authors = ["Claus F. Strasburger <1156864+cfstras@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "money_utils"}]

[tool.poetry.dependencies]
python = "^3.11"
asgiref = "3.7.2"
bleach = "3.3.0"
blinker = "1.7.0"
bokeh = "^3"
certifi = "2023.7.22"
chardet = "3.0.4"
charset-normalizer = "3.3.2"
click = "8.1.7"
colorama = "0.4.1"
contourpy = "1.1.1"
cython = "3.0.8"
django = "^3"
django-common-helpers = "0.9.2"
django-cron = "0.5.1"
django-request-logging = "0.7.0"
django-uwsgi = "0.2.2"
elementpath = "1.2.1"
fints = "3.0.0"
flask = "2.3.2"
flask-compress = "1.4.0"
fuzzywuzzy = "0.17.0"
idna = "2.8"
importlib-metadata = "7.0.1"
itsdangerous = "2.1.2"
jinja2 = "3.1.3"
markupsafe = "2.1.5"
mt-940 = "4.17.0"
packaging = "19.2"
pandas = "2.0.3"
pillow = "10.3.0"
pyparsing = "2.4.2"
python-dateutil = "2.8.2"
python-levenshtein = "0.12.1"
pytz = "2024.1"
pyyaml = "6.0.1"
requests = "2.31.0"
sepaxml = "2.2.0"
six = "1.12.0"
sqlalchemy = "1.3.0"
sqlparse = "0.5.0"
text-unidecode = "1.3"
tornado = "6.3.3"
typing-extensions = "4.9.0"
tzdata = "2024.1"
urllib3 = "1.26.18"
uwsgi = "2.0.22"
webencodings = "0.5.1"
werkzeug = "3.0.1"
xmlschema = "1.0.14"
xyzservices = "2023.10.1"
zipp = "3.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
