[project]
name = "money-utils"
version = "0.1.0"
description = "money-utils"
authors = [
    {name = "rfl", email = "rfl@flipdot.org"},
    {name = "0boro", email = "0boro@flipdot.org"},
    {name = "cfstras", email = "cfstras@flipdot.org"}
]
requires-python = ">=3.10"
dependencies = [
    "bokeh>=3.6.2",
    "django<4",
    "django-common>=0.1.51",
    "django-common-helpers>=0.9.2",
    "django-cron>=0.6.0",
    "django-uwsgi>=0.2.2",
    "fints>=4.2.3",
    "fuzzywuzzy>=0.18.0",
    "omegaconf>=2.3.0",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "python-levenshtein>=0.26.1",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.37",
    "uwsgi>=2.0.28",
]

[project.scripts]
money-utils = "money_utils:main"
answer-tan-request = "money_utils.bank.utils:answer_tan_request"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
]

